### Necessário para pegar o token
### Post
# @name loginAutenticado
POST http://localhost:20100/login HTTP/1.1
content-type: application/json

{
    "username": "qwe",    
    "passWord": "76d80224611fc919a5d54f0ff9fba446"
}

# Seta o token
@accessToken = {{loginAutenticado.response.body.$.token}}
@username = {{loginAutenticado.response.body.$.username}}


### Testes de Logradouro
## InsertLogradouro
## "LogradouroRest_{{datahora}}",
@datahora = {{$localDatetime iso8601}}
POST http://localhost:20100/acl/logradouro/v1/InsertLogradouro HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{   
    "nomelogradouro": "Rua Padre Isidoro Cordeiro Paranhos",
    "cidadeidfk": 1
}

### Testes de Logradouro
## GetALL
GET http://localhost:20100/acl/logradouro/v1/GetAllLogradouros HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
}

### Testes de Logradouro
## GetLogradouroByID
POST http://localhost:20100/acl/logradouro/v1/GetLogradouroByID HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "LogradouroID": 39
}




### Testes de Logradouro
## UpdateLogradouro
@datahora = {{$localDatetime iso8601}}
PUT http://localhost:20100/acl/logradouro/v1/UpdateLogradouro HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "LogradouroID": 23,    
    "nomelogradouro": "LogradMODiRest_{{datahora}}"
}


### Testes de Logradouro
## DeleteLogradouro
DELETE http://localhost:20100/acl/logradouro/v1/DeleteLogradouro HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "LogradouroID": 24  
}
