### Necessário para pegar o token
### Post
# @name loginAutenticado
POST http://localhost:20100/login HTTP/1.1
content-type: application/json

{
    "username": "qwe",    
    "passWord": "76d80224611fc919a5d54f0ff9fba446"
}

# Seta o token
@accessToken = {{loginAutenticado.response.body.$.token}}
@username = {{loginAutenticado.response.body.$.username}}


### Testes de Ocorrencia
## InsertOcorrencia
@datahora = {{$localDatetime iso8601}}
POST http://localhost:20100/acl/ocorrencia/v1/InsertOcorrencia HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "Removido": false, 
    "UnidBasicaSaudeIDFK": 4,
	"NomeSuspeito": "nome_{{datahora}}",	
    "datacadastro": "{{datahora}}",       
    "dataocorrencia": "{{datahora}}",
    "epidemiaidfk":17,
    "logradouroidfk":1,
    "numero": 20330,   
    "bairroidfk":24,
    "Localtrabalho":"local_{{datahora}}",
    "LogradourolocaltrabalhoIDFK": 1,
    "Numerolocaltrabalho": 200    
}


### Testes de Ocorrencia
## GetALL
GET http://localhost:20100/acl/ocorrencia/v1/GetAllOcorrencias HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
}

### Testes de Busca de Localização Geográfica: latitude e Longitude
## GetGeoAddress
GET http://localhost:20100/acl/ocorrencia/v1/GetGeoAddress
content-type: application/json
Authorization: Bearer {{accessToken}}

{
    
}

### Testes de Ocorrencia
## GetOcorrenciaByID
POST http://localhost:20100/acl/ocorrencia/v1/GetOcorrenciaByID HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "OcorrenciaID": 14
}




### Testes de Ocorrencia
## UpdateOcorrencia
@datahora = {{$localDatetime iso8601}}
PUT http://localhost:20100/acl/ocorrencia/v1/UpdateOcorrencia HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "OcorrenciaID": 6,
    "UnidBasicaSaudeIDFK": 4,
	"NomeSuspeito": "nome_{{datahora}}",	
    "datacadastro": "{{datahora}}",       
    "dataocorrencia": "{{datahora}}",
    "epidemiaidfk":17,
    "logradouroidfk":3,
    "numero": 341,    
    "bairroidfk":24,
    "Localtrabalho":"local_{{datahora}}",
    "LogradourolocaltrabalhoIDFK": 1,
    "Numerolocaltrabalho": 2       
}


### Testes de Ocorrencia
## DeleteOcorrencia
DELETE http://localhost:20100/acl/ocorrencia/v1/DeleteOcorrencia HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "OcorrenciaID": 7
}

