### Necessário para pegar o token
### Post
# @name loginAutenticado
POST http://localhost:20100/login HTTP/1.1
content-type: application/json

{
    "username": "qwe",    
    "passWord": "qwe"
}

# Seta o token
@accessToken = {{loginAutenticado.response.body.$.token}}
@username = {{loginAutenticado.response.body.$.username}}


### Testes de vdaBairro
## GetAll
GET http://localhost:20100/acl/bairro/v1/GetAllBairros HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
}

### Testes de vdaBairro
## GetBairrosByID
POST http://localhost:20100/acl/bairro/v1/GetBairrosByID HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "BairroID": 2
}


### Testes de vdaBairro
## InsertBairro
POST http://localhost:20100/acl/bairro/v1/InsertBairro HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "Removido": false,
    "Codigobairro": "vilaamerica",
    "Nomebairro": "Vila America"
}

### Testes de vdaBairro
## UpdateBairro
PUT http://localhost:20100/acl/bairro/v1/UpdateBairro HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "BairroID": 2,
    "Removido": false,
    "Codigobairro": "codB_2023-1Atu",
    "Nomebairro": "Boa Vista atu"
}


### Testes de vdaBairro
## DeleteBairro
DELETE http://localhost:20100/acl/bairro/v1/DeleteBairro HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "BairroID": 111  
}