## Post
# @name loginAutenticado
POST http://localhost:20100/login HTTP/1.1
content-type: application/json

{
    "userName": "qwe",    
    "passWord": "qwe"
}

# Seta o token
@accessToken = {{loginAutenticado.response.body.$.token}}
@accessTokenRefresh = {{loginAutenticado.response.body.$.tokenRefresh}}


### Renova o token

POST http://localhost:20100/seguranca/JwtRefreshToken HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessTokenRefresh}}

{
    "userName": "qwe"
}