### Necessário para pegar o token
### Post
# @name loginAutenticado
POST http://localhost:20100/login HTTP/1.1
Content-type: application/json

{
    "username": "qwe",    
    "passWord": "qwe"
}

# Seta o token
@accessToken = {{loginAutenticado.response.body.$.token}}
@username = {{loginAutenticado.response.body.$.username}}


### Testes de UBS
## InsertUBS
@datahora = {{$localDatetime 'YYMMDD h:mm:s:ms'}}
POST http://localhost:20100/acl/ubs/v1/InsertUBS HTTP/1.1
Content-type: application/json
Authorization: Bearer {{accessToken}}

{
      "codigoubs": "ParqueNacoes",
      "nomeubs": "Daniele Cristine Lamana",
      "bairroidfk": 53
}

### Testes de UBS
## GetALL
GET http://localhost:20100/acl/ubs/v1/GetAllUBSs HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
}

### Testes de UBS
## GetUBSByID
POST http://localhost:20100/acl/ubs/v1/GetUBSByID HTTP/1.1
Content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "unidBasicaSaudeID": 1
}


### Testes de UBS
## UpdateUBS
@datahora = {{$localDatetime iso8601}}
PUT http://localhost:20100/acl/ubs/v1/UpdateUBS HTTP/1.1
Content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "unidBasicaSaudeID": 1,
    "codigoubs": "c{{$localDatetime 'YYMMDD h:mm:s:ms'}}",
    "nomeubs": "n{{$localDatetime 'YYMMDD h:mm:s:ms'}}",
    "bairroidfk": 2
}


### Testes de UBS
## DeleteUBS
DELETE http://localhost:20100/acl/ubs/v1/DeleteUBS HTTP/1.1
Content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "unidBasicaSaudeID": 1  
}
