### Necessário para pegar o token
### Post
# @name loginAutenticado
POST http://localhost:20100/login HTTP/1.1
content-type: application/json

{
    "username": "qwe",    
    "passWord": "qwe"
}

# Seta o token
@accessToken = {{loginAutenticado.response.body.$.token}}



### Testes de aclGroup
## GetAll
GET http://localhost:20100/acl/group/v1/GetAllGroups HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
}


### GetGroupByID
POST http://localhost:20100/acl/group/v1/GetGroupByID HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "Groupid":4
}


### InsertGroup
@datahora = {{$localdatetime iso8601}}
POST http://localhost:20100/acl/group/v1/InsertGroup HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
"removido":false,
"codigogroup":"cod_{{datahora}}",
"tipogroup":"g",
"nomegroup":"Grupo_{{datahora}}"
}

### UpdateGroup
@datahora = {{$localdatetime iso8601}}
PUT http://localhost:20100/acl/group/v1/UpdateGroup HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
 "groupid": 129,
 "removido":false,
"codigogroup":"cod_{{datahora}}",
"tipogroup":"g",
"nomegroup":"Grupo_{{datahora}}"
}

### deleteGroup
@datahora = {{$localDatetime iso8601}}
DELETE  http://localhost:20100/acl/group/v1/DeleteGroup HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
 "groupid": 22
}

